blockExoticSubdeps: false
overrides:
  minimatch: ">=9.0.7"
  esbuild: ">=0.24.3"
  file-type: ">=21.3.1"
  vite: ">=6.4.2"
allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  protobufjs: true
  tesseract.js: true
onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - protobufjs
  - tesseract.js
